export const CURRENCIES_LIST_REQUEST = 'CURRENCIES_LIST_REQUEST'
export const CURRENCIES_LIST_SUCCESS = 'CURRENCIES_LIST_SUCCESS'
export const CURRENCIES_LIST_FAIL = 'CURRENCIES_LIST_FAIL'

export const FAVOURITE_ADDED = 'FAVOURITE_ADDED';
export const FAVOURITE_REMOVED = 'FAVOURITE_REMOVED';